CI, tox: fixing CI errors produced by ansible_lint
oVirt/ovirt-ansible-disaster-recovery pull request #95
Opened 2020-09-08 12:31 UTC by barpavel

Changing "shell:" to "command:" to fix the following error:
  [305] Use shell only when shell functionality is required

Signed-off-by: Pavel Bar <pbar@redhat.com>

2020-09-08 14:00 UTC, mnecas requested changes
Hi,
just note around the 207

2020-09-08 14:36 UTC, barpavel commented on tasks/run_unregistered_entities.yml
> +      set_fact: running_vms_fail_back="{% lookup('file', '{{ dr_running_vms }}') %}"
Thank you for your code review, fixed.

2020-09-08 14:36 UTC, barpavel commented on tasks/unregister_entities.yml
> +      set_fact: running_vms_fail_back="{% lookup('file', '{{ dr_running_vms }}') %}"
Fixed :)

2020-09-08 15:30 UTC, mnecas requested changes
Are you sure that the file mode should be 0666 instead of default 0664?

2020-09-09 08:11 UTC, barpavel commented
> Are you sure that the file mode should be 0666 instead of default 0664?

0664 or even 0644?

2020-09-09 08:19 UTC, mnecas commented
That depends on the usage. It can be 0644

2020-09-09 09:02 UTC, barpavel commented
> That depends on the usage. It could be 0644

Fixed, changed to 0644

2020-09-09 09:34 UTC, mnecas approved these changes
LGTM

2020-09-09 12:03 UTC, shenitzky approved these changes
Please run the full DR flow with at least 2 running HA VMs (failover + failback) to validate that all works

2020-09-14 14:40 UTC, barpavel commented
> Please run the full DR flow with at least 2 running HA VMs (failover + failback) to validate that all works

Done

2020-09-15 13:12 UTC, merged